#!/usr/bin/env python3

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "数据报表表结构Design_with_comments（4.15 v1.2）.sql"
TARGET = ROOT / "local_tidb_schema.sql"


def build_local_schema(raw_sql: str) -> tuple[str, int, int]:
    # The source document ends with an ES mapping JSON block. Local TiDB import
    # should only keep executable DDL statements.
    if "\n{\n" in raw_sql:
        raw_sql = raw_sql.split("\n{\n", 1)[0].rstrip() + "\n"

    ttl_pattern = re.compile(r"\s*/\*T!\[ttl\].*?\*/", re.DOTALL)
    raw_sql, ttl_count = ttl_pattern.subn("", raw_sql)

    partition_pattern = re.compile(
        r"\nPARTITION BY RANGE COLUMNS\([^)]*\)\n\([^;]*?\);",
        re.DOTALL,
    )
    raw_sql, partition_count = partition_pattern.subn(";\n", raw_sql)

    raw_sql = re.sub(r"\n{3,}", "\n\n", raw_sql).strip() + "\n"

    header = (
        "-- Generated by docs/业务需求/generate_local_tidb_schema.py\n"
        "-- Source of truth: 数据报表表结构Design_with_comments（4.15 v1.2）.sql\n"
        "-- Local TiDB variant: partition clauses, TTL hints, and trailing ES mapping are removed.\n\n"
    )

    return header + raw_sql, partition_count, ttl_count


def main() -> None:
    source_sql = SOURCE.read_text(encoding="utf-8")
    local_sql, partition_count, ttl_count = build_local_schema(source_sql)
    TARGET.write_text(local_sql, encoding="utf-8")
    print(
        f"Generated {TARGET.name} from {SOURCE.name} "
        f"(removed {partition_count} partition block(s), {ttl_count} TTL hint(s))."
    )


if __name__ == "__main__":
    main()
