#!/usr/bin/env python3

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "数据报表表结构Design_with_comments（5.5 v1.3）.sql"
TARGET = ROOT / "local_tidb_schema.sql"

FULL_REGRESSION_EXTERNAL_DDL = """
CREATE TABLE `marketing_external_metrics_daily` (
  `biz_date` date NOT NULL COMMENT '业务日期',
  `tenant_plat_id` bigint(20) NOT NULL COMMENT '商户平台ID, @link tenant_plat.id',
  `channel_id` bigint(20) NOT NULL COMMENT '渠道ID, @link channel.id',
  `ad_spend` decimal(19,4) DEFAULT NULL COMMENT '投放金额 / 买量成本',
  `access_pv` bigint(20) DEFAULT NULL COMMENT '访问PV',
  `access_uv` bigint(20) DEFAULT NULL COMMENT '访问UV',
  `download_click_uv` bigint(20) DEFAULT NULL COMMENT '下载点击UV',
  `source_name` varchar(64) NOT NULL DEFAULT 'full_regression_sample' COMMENT '外部数据来源标识',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '导入时间',
  PRIMARY KEY (`biz_date`,`tenant_plat_id`,`channel_id`),
  KEY `idx_external_metrics_channel_date` (`tenant_plat_id`,`channel_id`,`biz_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='本地FULL回归外部投放与流量指标样例表';
"""

COMMENT_LINK_RENAMES = {
    "game": "dim_game",
    "game_line": "dim_game_line",
    "game_line_series": "dim_game_line_series",
    "game_type": "dim_game_type",
    "report_channel_data_percent_config": "dim_report_channel_data_percent_config",
    "channel_player_statistics_of_day": "dim_channel_player_statistics_of_day",
    "vip": "dim_vip",
}


def extract_create_table_statements(sql_text: str) -> list[str]:
    statements: list[str] = []
    for match in re.finditer(
        r"CREATE\s+TABLE\s+`?[\w.]+`?\s*\(",
        sql_text,
        flags=re.IGNORECASE,
    ):
        index = match.end()
        depth = 1
        quote: str | None = None
        escaped = False
        while index < len(sql_text):
            char = sql_text[index]
            if quote:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == quote:
                    quote = None
                index += 1
                continue
            if char in {"'", '"', "`"}:
                quote = char
                index += 1
                continue
            if char == "(":
                depth += 1
            elif char == ")":
                depth -= 1
            elif char == ";" and depth == 0:
                statements.append(sql_text[match.start() : index + 1].strip())
                break
            index += 1
    return statements


def normalize_local_ddl(raw_sql: str) -> tuple[str, int, int]:
    # v1.3 can contain non-SQL JSON mapping blocks between CREATE TABLE blocks.
    # Keep only executable CREATE TABLE statements instead of truncating at JSON.
    create_statements = extract_create_table_statements(raw_sql)

    ttl_pattern = re.compile(r"\s*/\*T!\[ttl\].*?\*/", re.DOTALL)
    partition_pattern = re.compile(
        r"\nPARTITION BY RANGE COLUMNS\([^)]*\)\n\([^;]*?\);",
        re.DOTALL,
    )

    normalized: list[str] = []
    ttl_count = 0
    partition_count = 0
    for statement in create_statements:
        statement, removed_ttl = ttl_pattern.subn("", statement)
        ttl_count += removed_ttl
        statement, removed_partitions = partition_pattern.subn(";", statement)
        partition_count += removed_partitions
        for source_name, target_name in COMMENT_LINK_RENAMES.items():
            statement = re.sub(
                rf"@link\s+{re.escape(source_name)}\.",
                f"@link {target_name}.",
                statement,
                flags=re.IGNORECASE,
            )
        normalized.append(statement.strip())

    raw_sql = "\n\n".join(normalized).strip() + "\n"
    return raw_sql, partition_count, ttl_count


def build_local_schema(raw_sql: str) -> tuple[str, int, int]:
    ddl_sql, partition_count, ttl_count = normalize_local_ddl(raw_sql)
    if not re.search(r"CREATE\s+TABLE\s+`dim_vip`\s*\(", ddl_sql, re.IGNORECASE):
        raise ValueError("v1.3 schema must contain CREATE TABLE `dim_vip`")

    header = (
        "-- Generated by docs/业务需求/generate_local_tidb_schema.py\n"
        "-- Source of truth: 数据报表表结构Design_with_comments（5.5 v1.3）.sql\n"
        "-- Local TiDB variant: partition clauses, TTL hints, and trailing ES mapping are removed.\n"
        "-- VIP dimension: v1.3 defines dim_vip; source dump vip rows are mapped into dim_vip by the seed transformer.\n"
        "-- Local regression supplemental table: marketing_external_metrics_daily supports FULL external-metric regression cases.\n\n"
    )

    return (
        header
        + ddl_sql
        + "\n\n-- Supplemental external metrics for local FULL regression.\n"
        + FULL_REGRESSION_EXTERNAL_DDL.strip()
        + "\n",
        partition_count,
        ttl_count,
    )


def main() -> None:
    source_sql = SOURCE.read_text(encoding="utf-8")
    local_sql, partition_count, ttl_count = build_local_schema(source_sql)
    TARGET.write_text(local_sql, encoding="utf-8")
    print(
        f"Generated {TARGET.name} from {SOURCE.name} "
        f"(removed {partition_count} partition block(s), {ttl_count} TTL hint(s); "
        "ensured dim_vip and appended marketing_external_metrics_daily)."
    )


if __name__ == "__main__":
    main()
