apiVersion: apps/v1
kind: Deployment
metadata:
  name: wren-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wren-engine
  template:
    metadata:
      labels:
        app: wren-engine
    spec:
      volumes:
        - name: wren-data
          persistentVolumeClaim:
            claimName: wren-data-pvc
      containers:
        - name: wren-engine
          image: wren-engine:local
          ports:
            - containerPort: 8080
            - containerPort: 7432
          volumeMounts:
            - name: wren-data
              mountPath: /usr/src/app/etc
